Comment:
    type: entity
    table: comment
    indexes:
        fk_comment_comment1_idx:
            columns:
                - comment_id
        fk_comment_user_system1_idx:
            columns:
                - owner_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 300
            fixed: false
        text:
            type: string
            nullable: false
            length: 20000
            fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        comment:
            targetEntity: Comment
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                comment_id:
                    referencedColumnName: id
            orphanRemoval: false
        owner:
            targetEntity: UserSystem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                owner_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        userSystem:
            targetEntity: UserSystem
            cascade: {  }
            mappedBy: comment
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
