# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    my.oauth_aware.user_provider.service:
        class: AppBundle\Service\User\UserAuthorizationService
        arguments: ["@doctrine.orm.entity_manager"]
        
    user_data_service:
        class: AppBundle\Service\User\UserDataService
        arguments: ["@doctrine.orm.entity_manager"]

    comment_service:
        class: AppBundle\Service\CommentService
        arguments: ["@doctrine.orm.entity_manager"]
    
    ranking_service:
        class: AppBundle\Service\RankingService
        arguments: ["@doctrine.orm.entity_manager"]
    
    post_find_service:
        class: AppBundle\Service\PostFindService
        arguments: ["@doctrine.orm.entity_manager"]